# Your version: 0.6.0 Latest version: 0.8.0
# Generated by Neurodocker version 0.6.0
# Timestamp: 2022-04-05 13:16:21 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/kaczmarj/neurodocker

FROM neurodebian:stretch-non-free

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           git \
           num-utils \
           gcc \
           g++ \
           curl \
           build-essential \
           nano \
           graphviz \
           tree \
           git-annex-standalone \
           nano \
           less \
           ncdu \
           git-annex-remote-rclone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN test "$(getent passwd neuroscout)" || useradd --no-user-group --create-home --shell /bin/bash neuroscout
USER neuroscout

ENV CONDA_DIR="/opt/miniconda-latest" \
    PATH="/opt/miniconda-latest/bin:$PATH"
RUN export PATH="/opt/miniconda-latest/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean --all && sync \
    && conda create -y -q --name neuroscout_paper \
    && conda install -y -q --name neuroscout_paper \
           "python=3.8" \
           "nb_conda" \
           "nb_conda_kernels" \
           "nbconvert==6.4.5" \
           "nbformat" \
           "jupyter" \
    && sync && conda clean --all && sync \
    && bash -c "source activate neuroscout_paper \
    &&   pip install --no-cache-dir  \
             "seaborn" \
             "pyns==0.4.10" \
             "nilearn==0.8.0" \
             "altair" \
             "nimare==0.0.11" \
             "pymare==0.0.2" \
             "jupytext==1.11.5" \
             "ghp-import" \
             "jupyter-book==0.12.2" \
             "myst-nb==0.13.2" \
             "sympy==1.2" \
             "sphinx-book-theme" \
             "jupyter_contrib_nbextensions" \
             "nbval" \
             "duecredit"" \
    && rm -rf ~/.cache/pip/* \
    && sync \
    && sed -i '$isource activate neuroscout_paper' $ND_ENTRYPOINT

COPY [".", "/home/neuroscout/info"]

USER root

RUN chown -R neuroscout /home/neuroscout/info

RUN rm -rf /opt/conda/pkgs/*

USER neuroscout

RUN mkdir -p ~/.jupyter && echo c.NotebookApp.ip = \"0.0.0.0\" > ~/.jupyter/jupyter_notebook_config.py

WORKDIR /home/neuroscout/info/paper

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "neurodebian:stretch-non-free" \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "git", \
    \n        "num-utils", \
    \n        "gcc", \
    \n        "g++", \
    \n        "curl", \
    \n        "build-essential", \
    \n        "nano", \
    \n        "graphviz", \
    \n        "tree", \
    \n        "git-annex-standalone", \
    \n        "nano", \
    \n        "less", \
    \n        "ncdu", \
    \n        "git-annex-remote-rclone" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "neuroscout" \
    \n    ], \
    \n    [ \
    \n      "miniconda", \
    \n      { \
    \n        "conda_install": [ \
    \n          "python=3.8", \
    \n          "nb_conda", \
    \n          "nb_conda_kernels", \
    \n          "nbconvert==6.4.5", \
    \n          "nbformat", \
    \n          "jupyter" \
    \n        ], \
    \n        "pip_install": [ \
    \n          "seaborn", \
    \n          "pyns==0.4.10", \
    \n          "nilearn==0.8.0", \
    \n          "altair", \
    \n          "nimare==0.0.11", \
    \n          "pymare==0.0.2", \
    \n          "jupytext==1.11.5", \
    \n          "ghp-import", \
    \n          "jupyter-book==0.12.2", \
    \n          "myst-nb==0.13.2", \
    \n          "sympy==1.2", \
    \n          "sphinx-book-theme", \
    \n          "jupyter_contrib_nbextensions", \
    \n          "nbval", \
    \n          "duecredit" \
    \n        ], \
    \n        "create_env": "neuroscout_paper", \
    \n        "activate": true \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        ".", \
    \n        "/home/neuroscout/info" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "root" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "chown -R neuroscout /home/neuroscout/info" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "rm -rf /opt/conda/pkgs/*" \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "neuroscout" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mkdir -p ~/.jupyter && echo c.NotebookApp.ip = \\\"0.0.0.0\\\" > ~/.jupyter/jupyter_notebook_config.py" \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/home/neuroscout/info/paper" \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
